INSERT INTO `tracker222`.`time` ( `time_hour`) VALUES ( '1 am');
INSERT INTO `tracker222`.`time` ( `time_hour`) VALUES ( '2 am');
INSERT INTO `tracker222`.`time` ( `time_hour`) VALUES ( '3 am');
INSERT INTO `tracker222`.`time` ( `time_hour`) VALUES ( '4 am');
INSERT INTO `tracker222`.`time` ( `time_hour`) VALUES ( '5 am');
INSERT INTO `tracker222`.`time` ( `time_hour`) VALUES ( '6 am');
INSERT INTO `tracker222`.`time` ( `time_hour`) VALUES ( '7 am');
INSERT INTO `tracker222`.`time` ( `time_hour`) VALUES ( '8 am');
INSERT INTO `tracker222`.`time` ( `time_hour`) VALUES ( '9 am');
INSERT INTO `tracker222`.`time` ( `time_hour`) VALUES ( '10 am');
INSERT INTO `tracker222`.`time` ( `time_hour`) VALUES ( '11 am');
INSERT INTO `tracker222`.`time` (`time_hour`) VALUES ('12 am');
INSERT INTO `tracker222`.`time` (`time_hour`) VALUES ('1 pm');
INSERT INTO `tracker222`.`time` (`time_hour`) VALUES ('2 pm');
INSERT INTO `tracker222`.`time` (`time_hour`) VALUES ('3 pm');
INSERT INTO `tracker222`.`time` (`time_hour`) VALUES ('4 pm');
INSERT INTO `tracker222`.`time` (`time_hour`) VALUES ('5 pm');
INSERT INTO `tracker222`.`time` (`time_hour`) VALUES ('6 pm');
INSERT INTO `tracker222`.`time` (`time_hour`) VALUES ('7 pm');
INSERT INTO `tracker222`.`time` (`time_hour`) VALUES ('8 pm');
INSERT INTO `tracker222`.`time` (`time_hour`) VALUES ('9 pm');
INSERT INTO `tracker222`.`time` (`time_hour`) VALUES ('10 pm');
INSERT INTO `tracker222`.`time` (`time_hour`) VALUES ('11 pm');
INSERT INTO `tracker222`.`time` (`time_hour`) VALUES ('12 pm');